// SAA-C03 전용 부가 콘텐츠: 용어집
// COMPARES/KEYWORDS/TRAPS/DECISIONS는 index.html 본문에 이미 정의되어 있으므로 여기서는 GLOSSARY만 제공

window.SAA_GLOSSARY = [
  // ============ 스토리지 ============
  { cat:"스토리지", color:"#3b82f6", name:"Amazon S3", short:"객체 스토리지",
    desc:"무제한 용량·99.999999999% 내구성 객체 스토리지. 버킷 단위 관리. 정적 웹사이트, 데이터 레이크, 백업에 활용.", tags:["핵심"] },
  { cat:"스토리지", color:"#3b82f6", name:"S3 스토리지 클래스", short:"접근 빈도별 계층",
    desc:"Standard · Intelligent-Tiering(자동 이동) · Standard-IA · One Zone-IA · Glacier Instant/Flexible/Deep Archive. 예측 어려운 패턴 = Intelligent-Tiering.", tags:["비용"] },
  { cat:"스토리지", color:"#3b82f6", name:"S3 Transfer Acceleration", short:"글로벌 업로드 가속",
    desc:"CloudFront 엣지 로케이션 경유해 장거리 S3 업로드를 가속. 전 세계 사이트에서 단일 버킷 집계할 때 유용.", tags:["성능"] },
  { cat:"스토리지", color:"#3b82f6", name:"S3 Cross-Region Replication (CRR)", short:"리전 간 자동 복제",
    desc:"객체를 다른 리전 버킷에 자동 복제. DR·지연 감소·컴플라이언스용.", tags:["DR"] },
  { cat:"스토리지", color:"#3b82f6", name:"Amazon EBS", short:"EC2 블록 스토리지",
    desc:"단일 EC2 전용 블록 볼륨. gp3(범용)·io2(고IOPS)·st1/sc1(처리량·콜드). 스냅샷으로 백업.", tags:["블록"] },
  { cat:"스토리지", color:"#3b82f6", name:"Amazon EFS", short:"Linux용 공유 NFS",
    desc:"여러 EC2·Lambda·컨테이너가 동시 마운트하는 관리형 NFS. 자동 확장, 다중 AZ.", tags:["공유 파일"] },
  { cat:"스토리지", color:"#3b82f6", name:"Amazon FSx", short:"전용 파일 시스템",
    desc:"FSx for Windows(SMB·AD), FSx for Lustre(HPC·ML), FSx for NetApp ONTAP, FSx for OpenZFS.", tags:["파일 시스템"] },
  { cat:"스토리지", color:"#3b82f6", name:"AWS Snow Family", short:"오프라인 대용량 전송",
    desc:"Snowcone(8TB)·Snowball Edge(80TB)·Snowmobile(100PB). 네트워크 느릴 때 물리 이송.", tags:["이전"] },
  { cat:"스토리지", color:"#3b82f6", name:"Storage Gateway", short:"하이브리드 스토리지",
    desc:"File Gateway(SMB·NFS→S3), Volume Gateway(블록 iSCSI→S3), Tape Gateway(가상 테이프→S3·Glacier).", tags:["하이브리드"] },
  { cat:"스토리지", color:"#3b82f6", name:"AWS Backup", short:"중앙 백업 관리",
    desc:"EBS·RDS·DynamoDB·EFS·S3 등 통합 백업 정책·크로스 리전·크로스 계정 복제.", tags:["백업"] },

  // ============ 컴퓨팅 ============
  { cat:"컴퓨팅", color:"#10b981", name:"Amazon EC2", short:"가상 서버",
    desc:"다양한 인스턴스 패밀리: C(compute) · M(범용) · R(메모리) · I(I/O) · P/G(GPU) · Trn/Inf(ML) · X(대메모리) · T(버스트).", tags:["핵심"] },
  { cat:"컴퓨팅", color:"#10b981", name:"Auto Scaling Group", short:"자동 확장 그룹",
    desc:"CPU·네트워크·커스텀 메트릭 기반으로 EC2 인스턴스 수 자동 조절. 최소·최대·목표 설정.", tags:["확장"] },
  { cat:"컴퓨팅", color:"#10b981", name:"AWS Lambda", short:"서버리스 함수",
    desc:"코드만 업로드 → 이벤트 트리거로 실행. 최대 15분, 10GB 메모리, 동시 실행 한도. API Gateway·S3·EventBridge 연계.", tags:["서버리스"] },
  { cat:"컴퓨팅", color:"#10b981", name:"AWS Fargate", short:"서버리스 컨테이너",
    desc:"EC2 관리 없이 ECS·EKS 컨테이너 실행. 태스크 단위 과금. 무상태 워크로드에 적합.", tags:["서버리스", "컨테이너"] },
  { cat:"컴퓨팅", color:"#10b981", name:"Amazon ECS", short:"Docker 오케스트레이션",
    desc:"Docker 컨테이너 관리형. EC2 모드(인스턴스 관리) 또는 Fargate 모드(서버리스).", tags:["컨테이너"] },
  { cat:"컴퓨팅", color:"#10b981", name:"Amazon EKS", short:"관리형 Kubernetes",
    desc:"Kubernetes 컨트롤 플레인 관리형. 워커 노드는 EC2·Fargate. 복잡한 마이크로서비스 표준.", tags:["컨테이너"] },
  { cat:"컴퓨팅", color:"#10b981", name:"Spot Instance", short:"최대 90% 할인",
    desc:"남는 EC2 용량을 최대 90% 할인으로. 2분 전 종료 알림. 중단 허용 배치·내결함성 작업에.", tags:["비용"] },
  { cat:"컴퓨팅", color:"#10b981", name:"Reserved Instance / Savings Plans", short:"약정 할인",
    desc:"1·3년 약정으로 최대 72% 할인. Savings Plans(Compute/EC2)는 RI보다 유연.", tags:["비용"] },
  { cat:"컴퓨팅", color:"#10b981", name:"Elastic Beanstalk", short:"PaaS 배포",
    desc:"코드 업로드 → 자동으로 ELB·ASG·EC2·RDS 프로비저닝. 웹 앱 빠른 배포.", tags:["PaaS"] },
  { cat:"컴퓨팅", color:"#10b981", name:"AWS Batch", short:"배치 작업 관리",
    desc:"대량 배치를 큐에 넣고 자원 자동 할당. 과학 계산·ETL·금융 시뮬레이션.", tags:["배치"] },

  // ============ 데이터베이스 ============
  { cat:"데이터베이스", color:"#f59e0b", name:"Amazon RDS", short:"관계형 DB",
    desc:"MySQL·PostgreSQL·MariaDB·Oracle·SQL Server. Multi-AZ(장애조치)·Read Replica(읽기 분산).", tags:["관계형"] },
  { cat:"데이터베이스", color:"#f59e0b", name:"RDS Multi-AZ", short:"자동 장애조치",
    desc:"스탠바이를 다른 AZ에 동기 복제. 장애 시 자동 failover. 스탠바이는 읽기/쓰기 불가(순수 HA).", tags:["HA"] },
  { cat:"데이터베이스", color:"#f59e0b", name:"Amazon Aurora", short:"클라우드 네이티브 RDS",
    desc:"MySQL·PostgreSQL 호환, RDS보다 5배 빠름. Aurora Serverless v2, Global DB 지원.", tags:["관계형"] },
  { cat:"데이터베이스", color:"#f59e0b", name:"Amazon DynamoDB", short:"서버리스 NoSQL",
    desc:"밀리초 응답, 무한 확장 Key-Value/Document. 파티션키 설계가 핵심. Global Tables로 멀티 리전.", tags:["NoSQL"] },
  { cat:"데이터베이스", color:"#f59e0b", name:"DynamoDB DAX", short:"마이크로초 캐시",
    desc:"DynamoDB 앞단 관리형 인메모리 캐시. 애플리케이션 코드 거의 수정 없음.", tags:["캐시"] },
  { cat:"데이터베이스", color:"#f59e0b", name:"Amazon ElastiCache", short:"관리형 Redis/Memcached",
    desc:"Redis(복제·지속성·Pub-Sub)·Memcached(멀티스레드·단순). DB 부하 감소·세션 저장.", tags:["캐시"] },
  { cat:"데이터베이스", color:"#f59e0b", name:"Amazon Redshift", short:"데이터 웨어하우스",
    desc:"컬럼형 OLAP, PB 규모 분석. Redshift Spectrum으로 S3 직접 쿼리.", tags:["DW"] },
  { cat:"데이터베이스", color:"#f59e0b", name:"Amazon Neptune", short:"그래프 DB",
    desc:"관계 많은 데이터(사기·SNS·추천). Gremlin·SPARQL 쿼리. Neptune ML로 그래프 ML.", tags:["그래프"] },
  { cat:"데이터베이스", color:"#f59e0b", name:"Amazon DocumentDB", short:"MongoDB 호환",
    desc:"MongoDB API 호환. 관리형 문서 DB. JSON 중심 애플리케이션.", tags:["NoSQL"] },
  { cat:"데이터베이스", color:"#f59e0b", name:"Amazon Timestream", short:"시계열 DB",
    desc:"IoT·모니터링 시계열 데이터 전용. 자동 계층화 저장.", tags:["시계열"] },
  { cat:"데이터베이스", color:"#f59e0b", name:"Amazon Keyspaces", short:"Cassandra 호환",
    desc:"Cassandra API 호환 관리형 와이드 컬럼 DB.", tags:["NoSQL"] },

  // ============ 네트워크 ============
  { cat:"네트워크", color:"#8b5cf6", name:"Amazon VPC", short:"가상 네트워크",
    desc:"격리된 가상 네트워크. 서브넷(퍼블릭/프라이빗), 라우트 테이블, 보안 그룹, NACL 구성.", tags:["핵심"] },
  { cat:"네트워크", color:"#8b5cf6", name:"Internet Gateway / NAT Gateway", short:"인터넷 출입",
    desc:"IGW: VPC↔인터넷 양방향. NAT GW: 프라이빗 서브넷에서 아웃바운드만(AZ별 배치).", tags:["게이트웨이"] },
  { cat:"네트워크", color:"#8b5cf6", name:"VPC Endpoint / PrivateLink", short:"프라이빗 AWS 접근",
    desc:"Gateway Endpoint(S3·DynamoDB 무료) / Interface Endpoint(PrivateLink, ENI 기반 유료). 인터넷 미경유.", tags:["프라이빗"] },
  { cat:"네트워크", color:"#8b5cf6", name:"Security Group vs NACL", short:"방화벽 2계층",
    desc:"SG(인스턴스·stateful·Allow 규칙만). NACL(서브넷·stateless·Allow/Deny). 거의 SG 우선 사용.", tags:["보안"] },
  { cat:"네트워크", color:"#8b5cf6", name:"AWS Direct Connect", short:"전용선",
    desc:"물리 전용 회선 (1·10·100Gbps). 안정적 대역폭, 낮은 지연. 설치 수 주~수 개월 소요.", tags:["하이브리드"] },
  { cat:"네트워크", color:"#8b5cf6", name:"Site-to-Site VPN", short:"IPSec 터널",
    desc:"온프레미스 라우터와 AWS VGW 사이 IPSec 터널. 빠른 설치, 인터넷 경유.", tags:["하이브리드"] },
  { cat:"네트워크", color:"#8b5cf6", name:"Transit Gateway", short:"허브형 연결",
    desc:"여러 VPC·온프레미스를 허브로 단일 연결. 피어링 복잡도 해소.", tags:["네트워크 허브"] },
  { cat:"네트워크", color:"#8b5cf6", name:"Amazon Route 53", short:"DNS + 라우팅 정책",
    desc:"DNS 서비스 + Simple/Weighted/Latency/Geolocation/Failover/Multi-Value 라우팅. 헬스체크 지원.", tags:["DNS"] },
  { cat:"네트워크", color:"#8b5cf6", name:"Amazon CloudFront", short:"글로벌 CDN",
    desc:"엣지 로케이션에서 정적·동적 콘텐츠 캐싱. Lambda@Edge·CloudFront Functions로 엣지 로직.", tags:["CDN"] },
  { cat:"네트워크", color:"#8b5cf6", name:"AWS Global Accelerator", short:"고정 IP + Anycast",
    desc:"Anycast IP로 최적 리전 라우팅. 방화벽 화이트리스트 필요 시 유리. TCP/UDP 지원.", tags:["글로벌"] },
  { cat:"네트워크", color:"#8b5cf6", name:"Elastic Load Balancer", short:"로드 밸런서",
    desc:"ALB(HTTP/HTTPS·L7·경로/호스트 기반)·NLB(L4·고정 IP·초저지연)·GWLB(방화벽 삽입).", tags:["LB"] },

  // ============ 메시징·스트리밍 ============
  { cat:"메시징", color:"#ec4899", name:"Amazon SQS", short:"큐",
    desc:"Standard(고처리량·순서 미보장)·FIFO(정확히 1회·순서). DLQ로 재처리 실패 분리.", tags:["큐"] },
  { cat:"메시징", color:"#ec4899", name:"Amazon SNS", short:"Pub/Sub 토픽",
    desc:"토픽 → 여러 구독자(SQS·Lambda·HTTP·이메일·SMS). 팬아웃 패턴.", tags:["Pub/Sub"] },
  { cat:"메시징", color:"#ec4899", name:"Amazon EventBridge", short:"이벤트 버스",
    desc:"AWS 서비스·SaaS·커스텀 이벤트를 규칙 기반 라우팅. 스케줄드 이벤트 지원.", tags:["이벤트"] },
  { cat:"메시징", color:"#ec4899", name:"Amazon Kinesis Data Streams", short:"실시간 스트리밍",
    desc:"샤드 기반 대용량 스트리밍. 파티션키로 순서 보장. 실시간 분석·처리.", tags:["스트리밍"] },
  { cat:"메시징", color:"#ec4899", name:"Amazon MSK", short:"관리형 Kafka",
    desc:"Apache Kafka 관리형. 기존 Kafka 생태계 이전할 때.", tags:["스트리밍"] },
  { cat:"메시징", color:"#ec4899", name:"AWS Step Functions", short:"워크플로 오케스트레이션",
    desc:"Lambda·ECS·API 호출을 상태 머신으로 조합. 재시도·에러 처리·분기 관리.", tags:["오케스트레이션"] },

  // ============ 보안 ============
  { cat:"보안", color:"#ef4444", name:"AWS IAM", short:"권한 관리",
    desc:"User·Group·Role·Policy. Least Privilege 원칙. IAM Identity Center(구 SSO)로 멀티 계정 SSO.", tags:["핵심"] },
  { cat:"보안", color:"#ef4444", name:"AWS KMS", short:"암호화 키 관리",
    desc:"고객 관리형 키(CMK). S3·EBS·RDS·Lambda 등 통합. 자동 키 회전.", tags:["암호화"] },
  { cat:"보안", color:"#ef4444", name:"AWS CloudHSM", short:"전용 HSM",
    desc:"FIPS 140-2 Level 3 전용 HSM. 규제 요구 시. KMS보다 비싸고 관리 부담.", tags:["암호화"] },
  { cat:"보안", color:"#ef4444", name:"AWS Secrets Manager", short:"비밀번호·API 키",
    desc:"비밀 저장·자동 회전(RDS 등 통합). Parameter Store보다 기능 풍부·유료.", tags:["비밀 관리"] },
  { cat:"보안", color:"#ef4444", name:"AWS Certificate Manager (ACM)", short:"무료 SSL/TLS",
    desc:"AWS 서비스용 SSL/TLS 인증서 무료 발급·자동 갱신. ALB·CloudFront에 바로 연결.", tags:["인증서"] },
  { cat:"보안", color:"#ef4444", name:"AWS WAF", short:"웹 애플리케이션 방화벽",
    desc:"SQL 인젝션·XSS·봇 차단. CloudFront·ALB·API Gateway·AppSync에 연결.", tags:["웹 보안"] },
  { cat:"보안", color:"#ef4444", name:"AWS Shield", short:"DDoS 방어",
    desc:"Standard(무료, L3/4)·Advanced(유료, L7 + 24/7 대응). CloudFront·Route 53에 자동 적용.", tags:["DDoS"] },
  { cat:"보안", color:"#ef4444", name:"Amazon GuardDuty", short:"위협 탐지",
    desc:"ML 기반 VPC Flow Logs·DNS·CloudTrail 분석. 악성 IP·비정상 행위 탐지.", tags:["위협 탐지"] },
  { cat:"보안", color:"#ef4444", name:"Amazon Inspector", short:"취약점 스캔",
    desc:"EC2·ECR 이미지·Lambda의 CVE·OS 취약점 자동 스캔·우선순위.", tags:["취약점"] },
  { cat:"보안", color:"#ef4444", name:"Amazon Macie", short:"S3 민감 데이터 탐지",
    desc:"ML로 S3 객체에서 PII·금융 정보 자동 분류·탐지. GDPR·HIPAA 준수.", tags:["데이터 보호"] },
  { cat:"보안", color:"#ef4444", name:"AWS Network Firewall", short:"VPC 네트워크 방화벽",
    desc:"VPC 경계에서 상태 기반 IDS/IPS. 여러 VPC를 중앙 정책으로 보호.", tags:["네트워크"] },
  { cat:"보안", color:"#ef4444", name:"AWS Security Hub", short:"보안 통합 대시보드",
    desc:"GuardDuty·Inspector·Macie·Config·3rd party 발견사항 통합. 표준 프레임워크 준수 평가.", tags:["통합"] },

  // ============ 모니터링·거버넌스 ============
  { cat:"모니터링", color:"#06b6d4", name:"Amazon CloudWatch", short:"메트릭·로그·알람",
    desc:"AWS·커스텀 메트릭, 로그 스트림, Alarm, Dashboards, Events(구). 거의 모든 서비스에서 기본.", tags:["핵심"] },
  { cat:"모니터링", color:"#06b6d4", name:"AWS CloudTrail", short:"API 감사 로그",
    desc:"모든 AWS API 호출 기록(Management/Data/Insight Events). 조직 내 다계정 통합. 규정 준수 필수.", tags:["감사"] },
  { cat:"모니터링", color:"#06b6d4", name:"AWS X-Ray", short:"분산 추적",
    desc:"마이크로서비스 간 요청 추적·병목 분석. API Gateway·Lambda·ECS 자동 통합.", tags:["추적"] },
  { cat:"모니터링", color:"#06b6d4", name:"AWS Config", short:"구성 추적·규정 평가",
    desc:"리소스 변경 이력 + 규칙 기반 자동 준수 평가 + 자동 리미디에이션.", tags:["거버넌스"] },
  { cat:"모니터링", color:"#06b6d4", name:"AWS Trusted Advisor", short:"모범 사례 권고",
    desc:"비용·성능·보안·내결함성·서비스 한도 5축 권고. Business/Enterprise 플랜에서 전체 기능.", tags:["권고"] },
  { cat:"모니터링", color:"#06b6d4", name:"AWS Systems Manager (SSM)", short:"운영 자동화",
    desc:"Parameter Store·Session Manager(키 없이 EC2 접근)·Patch Manager·Automation·Run Command.", tags:["운영"] },
  { cat:"모니터링", color:"#06b6d4", name:"AWS Organizations", short:"멀티 계정 관리",
    desc:"여러 계정 묶어 중앙 청구, SCP(Service Control Policy)로 조직 단위 권한 제한.", tags:["거버넌스"] },
  { cat:"모니터링", color:"#06b6d4", name:"AWS Audit Manager", short:"컴플라이언스 자동화",
    desc:"SOC·PCI·HIPAA·ISO 프레임워크 매핑 + 감사 증거 자동 수집.", tags:["컴플라이언스"] },
  { cat:"모니터링", color:"#06b6d4", name:"AWS Artifact", short:"AWS 컴플라이언스 리포트",
    desc:"SOC·ISO·PCI 공식 리포트 포털. 서드파티 리포트 알림 구독.", tags:["컴플라이언스"] },
  { cat:"모니터링", color:"#06b6d4", name:"AWS Cost Explorer / Budgets", short:"비용 가시성",
    desc:"Cost Explorer(분석 UI)·Cost and Usage Report(상세)·Budgets(알림)·Savings Plans 추천.", tags:["비용"] },

  // ============ 분석·ETL ============
  { cat:"분석", color:"#0ea5e9", name:"Amazon Athena", short:"S3 서버리스 SQL",
    desc:"S3 데이터에 직접 SQL. Presto 기반. Parquet·ORC 쓰면 비용·성능↑. 스캔량 기반 과금.", tags:["쿼리"] },
  { cat:"분석", color:"#0ea5e9", name:"AWS Glue", short:"서버리스 ETL + 카탈로그",
    desc:"Spark 기반 ETL Job + Data Catalog(Athena·Redshift 공유) + 크롤러·Glue Studio·DataBrew.", tags:["ETL"] },
  { cat:"분석", color:"#0ea5e9", name:"Amazon EMR", short:"Hadoop/Spark 클러스터",
    desc:"Spark·Hadoop·Presto·HBase 관리형. 임시 클러스터로 비용↓. Serverless도 지원.", tags:["빅데이터"] },
  { cat:"분석", color:"#0ea5e9", name:"Amazon OpenSearch Service", short:"검색·로그·벡터",
    desc:"Elasticsearch 기반 검색·로그 분석·k-NN 벡터 검색. Kibana 대시보드.", tags:["검색"] },
  { cat:"분석", color:"#0ea5e9", name:"Amazon QuickSight", short:"BI 대시보드",
    desc:"SPICE 인메모리 엔진으로 빠른 대시보드. Q(자연어 질의) 기능 포함.", tags:["BI"] },
  { cat:"분석", color:"#0ea5e9", name:"AWS Lake Formation", short:"데이터 레이크 거버넌스",
    desc:"S3 데이터 레이크에 세분화된 접근 제어·태그 기반 정책. Glue 카탈로그와 통합.", tags:["거버넌스"] },
  { cat:"분석", color:"#0ea5e9", name:"Amazon Kinesis Data Firehose", short:"스트림 적재",
    desc:"실시간 스트림을 S3·Redshift·OpenSearch·Splunk에 자동 적재. 압축·변환 지원.", tags:["스트리밍"] },
  { cat:"분석", color:"#0ea5e9", name:"Amazon Kinesis Data Analytics", short:"스트림 SQL",
    desc:"Apache Flink 기반 실시간 스트림 분석. 윈도 집계·이상 탐지.", tags:["스트리밍"] },

  // ============ 마이그레이션 ============
  { cat:"마이그레이션", color:"#84cc16", name:"AWS DMS", short:"DB 이전",
    desc:"Database Migration Service. 온라인 무중단 DB 이전. CDC(변경 데이터 캡처) 지원.", tags:["DB 이전"] },
  { cat:"마이그레이션", color:"#84cc16", name:"AWS SCT", short:"스키마 변환",
    desc:"이종 DB 스키마·저장 프로시저 변환(Oracle→PostgreSQL 등). DMS와 함께 사용.", tags:["DB 이전"] },
  { cat:"마이그레이션", color:"#84cc16", name:"AWS MGN", short:"서버 이전",
    desc:"Application Migration Service. 물리·가상 서버를 EC2로 리프트앤시프트.", tags:["서버 이전"] },
  { cat:"마이그레이션", color:"#84cc16", name:"AWS DataSync", short:"대용량 데이터 이전",
    desc:"NFS·SMB·HDFS·S3 간 대용량 데이터 고속 동기화. 온프레↔AWS 이전에 주로.", tags:["데이터 이전"] },
  { cat:"마이그레이션", color:"#84cc16", name:"AWS Transfer Family", short:"관리형 SFTP/FTP/FTPS",
    desc:"S3·EFS 대상 관리형 SFTP·FTP·FTPS. 기존 파일 전송 워크플로 유지.", tags:["파일 전송"] },
  { cat:"마이그레이션", color:"#84cc16", name:"AWS Snow Family", short:"오프라인 물리 이송",
    desc:"네트워크가 느릴 때 물리 장치로 데이터 이송. Snowcone·Snowball Edge·Snowmobile.", tags:["오프라인"] },

  // ============ 개발자·기타 ============
  { cat:"개발자도구", color:"#a78bfa", name:"AWS CloudFormation", short:"IaC (JSON/YAML)",
    desc:"인프라를 템플릿으로 선언. Stack·Change Set. Drift 감지.", tags:["IaC"] },
  { cat:"개발자도구", color:"#a78bfa", name:"AWS CDK", short:"IaC (코드 기반)",
    desc:"TypeScript·Python 등 코드로 CloudFormation 생성. 추상화 레벨 높음.", tags:["IaC"] },
  { cat:"개발자도구", color:"#a78bfa", name:"AWS CodePipeline / CodeBuild / CodeDeploy / CodeCommit", short:"CI/CD 스택",
    desc:"Commit(Git 저장소)·Build(빌드)·Deploy(배포)·Pipeline(오케스트레이션). 통합 파이프라인.", tags:["CI/CD"] },
  { cat:"개발자도구", color:"#a78bfa", name:"AWS Amplify", short:"프론트엔드 풀스택",
    desc:"웹·모바일 프론트엔드 호스팅 + 인증(Cognito)·API(AppSync)·스토리지 통합.", tags:["프론트엔드"] },
  { cat:"개발자도구", color:"#a78bfa", name:"Amazon API Gateway", short:"REST/WebSocket API",
    desc:"REST·HTTP·WebSocket API 관리형. Lambda·ECS·HTTP 백엔드. 인증·스로틀링·캐싱.", tags:["API"] },
  { cat:"개발자도구", color:"#a78bfa", name:"Amazon Cognito", short:"사용자 인증",
    desc:"User Pools(로그인·회원가입) + Identity Pools(AWS 임시 자격). 소셜 로그인·MFA 지원.", tags:["인증"] },

  // ============ AI/ML (기본) ============
  { cat:"AI/ML", color:"#f97316", name:"Amazon SageMaker", short:"ML 전주기 플랫폼",
    desc:"노트북·학습·튜닝·배포·모니터링까지. JumpStart(사전학습 모델)·Canvas(노코드)·Clarify(편향)·Model Monitor.", tags:["ML"] },
  { cat:"AI/ML", color:"#f97316", name:"Amazon Bedrock", short:"관리형 FM",
    desc:"Claude·Titan·Nova·Llama 등 FM API. Knowledge Bases(RAG)·Agents·Guardrails 제공.", tags:["생성형 AI"] },
  { cat:"AI/ML", color:"#f97316", name:"Amazon Comprehend", short:"NLP 관리형",
    desc:"감정·엔티티·키프레이즈·독성 분석. Comprehend Medical은 의료 엔티티.", tags:["NLP"] },
  { cat:"AI/ML", color:"#f97316", name:"Amazon Rekognition", short:"이미지·비디오 인식",
    desc:"객체·얼굴·텍스트·모더레이션·커스텀 라벨. 얼굴 수집·비식별 정책 유의.", tags:["비전"] },
  { cat:"AI/ML", color:"#f97316", name:"Amazon Transcribe / Polly / Translate", short:"음성·번역",
    desc:"Transcribe(음성→텍스트), Polly(텍스트→음성), Translate(번역). 자막·더빙 파이프라인.", tags:["언어"] },
  { cat:"AI/ML", color:"#f97316", name:"Amazon Kendra", short:"엔터프라이즈 검색",
    desc:"자연어 질의, ML 랭킹. 사내 문서 통합 검색의 표준.", tags:["검색"] },
  { cat:"AI/ML", color:"#f97316", name:"Amazon Personalize", short:"추천 엔진",
    desc:"사용자-아이템 상호작용 기반 실시간 개인화 추천.", tags:["추천"] }
];
